### ISSUE TITLE
SDFITSload.summary() needs concision

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#10]
Too verbose now, needs concise mode like gbtidl

**Comment by mpound** [comment]
this is done in mwp-devel.  
There is still an issue with a factor of two in # integrations versus gbtidl (dysh x2 more).  could be sig/ref count?

**Comment by astrofle** [comment]
This is still a factor of 2 off for the data in subbeamnod-Ka. Now it is half of what GBTIDL reports.

**Comment by mpound** [comment]
This is fixed in release branch.

**Comment by astrofle** [comment]
I just pulled from release and I'm getting half the integrations for Nod scans in `/home/dysh/example_data/subbeamnod-Ka/data/TRCO_230413_Ka.raw.vegas/TRCO_230413_Ka.raw.vegas.A.fits`. It reports 30, while GBTIDL reports 60.

**Comment by mpound** [comment]
hmm..it is correct for "Unknown" and "SubBeam" in that file, but incorrect for "Nod", yet SubBeam and Nod both have the same procsize.  I must confess confusion now how GBTIDL is counting integrations.

**Comment by mpound** [comment]
oooh....hahah check out this comment in line_index__define.pro
; Algorithm for determining integration numbers (0-based), given the sdfits rows of a scan.
; This is simple: just use the DATE-OBS column values.

**Comment by astrofle** [comment]
Fixed by [33475ad](https://github.com/GreenBankObservatory/dysh/commit/33475ade4d9befba63248722357e67128c71297c).
Hopefully for good now :)
