### ISSUE TITLE
Hardcoded file paths in notebooks

### ISSUE THREAD

**Issue by vcatlett** [GreenBankObservatory/dysh#100]
The notebooks in dysh/notebooks have hardcoded paths to files. We should probably change those to wgets or provide instructions for downloading the files and then putting the correct path.

**Comment by astrofle** [comment]
Commit [9f55b15](https://github.com/GreenBankObservatory/dysh/commit/9f55b1590d11e491f805d3e5ba671e482c3862e6) a note about the size of the file being used.

**Comment by tchamberlin** [comment]
Is this still an issue?

**Comment by mpound** [comment]
This is fixed for example notebooks  as of 0.2.0b (but see #139 about wget).  developer notebooks may have hardcoded paths, but that's on them.    Closing this.
