### ISSUE TITLE
Calibration of OffOn scans through getps cannot find the scan pairs

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#102]
Calibrating a OffOn observation using `getps` raises an error because it assumes that the Off scan takes place after the On scan.
[Here's an example notebook](https://github.com/GreenBankObservatory/dysh/blob/multifits/notebooks/developer/test_OffOn.ipynb).

The notebooks lives in the multifits branch, but the error is also present in release-0.2.0.

**Comment by mpound** [comment]
checked in a fix for this in multifits branch.   test_multifits.ipynb now runs.  

Question:   Should a selection ifnum/plnum combination that results in no scans
a) Raise an exception
b) print a warning and return an empty ScanBlock

Currently the code does b, but a may be the better choice for the general user.

**Comment by astrofle** [comment]
I think raising an informative exception is better. It would be easier for
the users to realize something is missing, and does not require checking
for empty ScanBlocks.

I'll check it as soon as I can.

Thanks!

**Comment by mpound** [comment]
ok changed to exceptions.  also found another little bug I patched

**Comment by astrofle** [comment]
Hi Marc,

I checked the changes, but it still does not work for me.

If you run the following, `dysh` still raises a warning. Not ideal in my opinion (there's one scan with that IF number, the user does not need to know that the combination is not in all the files).
```
ps_scans = sdf.getps(6, ifnum=2)

    FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.A.fits
    FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.A.fits
    FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.B.fits
    FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.C.fits 
    FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.D.fits
    /home/sandboxes/psalas/Dysh/dysh-multifits/src/dysh/spectra/core.py:333: RuntimeWarning: Mean of empty slice
    meandiff = np.nanmean(calon[chrng]) - np.nanmean(caloff[chrng])
    /home/sandboxes/psalas/Dysh/dysh-multifits/src/dysh/fits/gbtfitsload.py:949: UserWarning: no on/off scans found for given selection
    warnings.warn("no on/off scans found for given selection")
```
If that is for debugging, no problem.

And, if you change the `ifnum` to another one it raises an exception, even if the data is in there:
```
ps_scans = sdf.getps(6, ifnum=0)
```
results in:
```
FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.A.fits
FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.B.fits
FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.C.fits
FILE  /home/sandboxes/psalas/Dysh/dysh/testdata/AGBT18B_354_03.raw.vegas/AGBT18B_354_03.raw.vegas.A.fits
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 ps_scans = sdf.getps(6, ifnum=0)

File /home/sandboxes/psalas/Dysh/dysh-multifits/src/dysh/fits/gbtfitsload.py:382, in GBTFITSLoad.getps(self, scans, bintable, **kwargs)
    380     continue
    381 # add ifnum,plnum
--> 382 rows = self.onoff_rows(scans, ifnum=ifnum, plnum=plnum, bintable=bintable, fitsindex=i)
    383 # do not pass scan list here. We need all the cal rows. They will
    384 # be intersected with scan rows in PSScan
    385 # add ifnum,plnum
    386 calrows = self.calonoff_rows(scans=None, bintable=bintable, fitsindex=i)

File /home/sandboxes/psalas/Dysh/dysh-multifits/src/dysh/fits/gbtfitsload.py:1099, in GBTFITSLoad.onoff_rows(self, scans, ifnum, plnum, bintable, fitsindex)
   1097 # scans is now a dict of "ON" "OFF
   1098 for key in scans:
-> 1099     rows[key] = self.scan_rows(scans[key], ifnum, plnum, bintable)
   1100 return rows

File /home/sandboxes/psalas/Dysh/dysh-multifits/src/dysh/fits/gbtfitsload.py:1132, in GBTFITSLoad.scan_rows(self, scans, ifnum, plnum, bintable, fitsindex)
   1130 rows = list(df.index)
   1131 if len(rows) == 0:
-> 1132     raise Exception(f"Scans {scans} not found in bintable {bintable}")
   1133 return rows

Exception: Scans [] not found in bintable None
```

**Comment by astrofle** [comment]
Hi Marc,
I checked, and `IFNUM=0` is present in the SDFITS file.
```python
from dysh.fits.gbtfitsload import GBTFITSLoad
import dysh.util as util

# Point it to the testdata directory on the root dysh directory.
testdata = util.get_project_testdata()
data_path = testdata  / "AGBT18B_354_03.raw.vegas"

sdf = GBTFITSLoad(data_path)
sdf.udata("IFNUM")
    [2, 1, 0, 3]

for ifnum in sdf.udata("IFNUM"):
    try:
        ps_scan = sdf.getps([6], ifnum=ifnum)
    except Exception as e:
        print(f"Exception raised for ifnum={ifnum}")
        print(e)
```
the for loop raises the `Exception` for `IFNUM=0,1,3`.

**Comment by mpound** [comment]
There were two problems.  
1) in certain methods, not checking if plnum or ifnum was None before doing a downselect 
2) in certain methods, not passing along the fitsindex that indicates which file to use.

try it now.

**Comment by astrofle** [comment]
🎉 it works!
[4c099af](https://github.com/GreenBankObservatory/dysh/commit/4c099afed5d1fd51a966cba004513a300936d986) has a passing test in it.

Some things that we should decide on before closing this issue are the warnings and print statements.

1. Do we want to keep raising a warning if there are no rows matching the selection criteria in one or more of the SDFITS files (i.e. Do we want to keep [this warning](https://github.com/GreenBankObservatory/dysh/blob/4c099afed5d1fd51a966cba004513a300936d986/src/dysh/fits/gbtfitsload.py#L959)?)
2. [Do we want to keep showing the filenames](https://github.com/GreenBankObservatory/dysh/blob/4c099afed5d1fd51a966cba004513a300936d986/src/dysh/fits/gbtfitsload.py#L942)?

**Comment by mpound** [comment]
I've removed the print statements.  However, pytest fails for me because the NGC2782  FITS file is not present.  Is it supposed to be in the repo? 

FAILED src/dysh/spectra/tests/test_scan.py::TestPSScan::test_compare_with_GBTIDL_2
Exception: testdata/TGBT21A_501_11/NGC2782/TGBT21A_501_11_NGC2782.raw.vegas.A.fits is not a file or directory path

**Comment by astrofle** [comment]
The test data should be in multifits now.
Sorry.
