### ISSUE TITLE
Time averaging with NaN integrations (blanked) results in a NaN time average

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#103]
It is often the case that VEGAS will write an integration filled with NaNs (blanked in GBO lingo) when there's not enough time to complete an integration. This usually happens at the end of a scan.
At this point in time, `dysh` does not handle this properly, resulting in time averages that contain only NaN values.
[Here is an example notebook showing this](https://github.com/GreenBankObservatory/dysh/blob/multifits/notebooks/developer/test_timeaverage_with_NaNs.ipynb).

**Comment by mpound** [comment]
this is specific to averaging of data (e.g. timeaveraging) .   fix will be to replace np.average with np.nanmean for instannce

**Comment by astrofle** [comment]
Just to clarify. The raw data, as it comes from the SDFITS filler, should not have portions of a spectrum with NaN values. It is either all of the  channels are NaN (for blanked integrations), or they all have valid values. If there are ranges of channels with NaN values it must be because a user set those to NaN.
If we have to do anything about the case where a user set some values to NaN, ignoring the NaN channels is the appropriate behavior. In these cases, `dysh` should also keep track of the weights (exposure times particularly) appropriately.i.e., if we are time averaging two spectra

**Comment by mpound** [comment]
Should be fixed in latest multifits commit.  Blanked integrations are not included in time average.    "Bad" (nan) channels, not fully blanked spectrum, are still included.  Note we do have an example of a nan channel that is not set by user, the TP scans have NaN in channel 0 and 3072.

Also, I just saw that the test data files have moved, so the notebooks need to be updated again.

**Comment by astrofle** [comment]
Thanks Marc! This is working.
I'll close the issue as soon as I update the notebooks and write a test case that can be shipped with the codebase.
