### ISSUE TITLE
Create basic Dysh shell

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#106]
```sh
$ dysh
```

Should launch the user into an IPython session where relevant dysh modules have been pre-loaded.

Optional: Dysh-specific IPython profile is used, so that there's no leakage between dysh and non-dysh IPython sessions

**Comment by teuben** [comment]
Here's the example I cooked up, with the echo's just an example:

#
if [ -e ~/.ipython/profile_dysh ]; then
    ipython --profile=dysh
else
    echo "Generating a new ipython dysh profile"
    ipython profile create dysh
    # or copy from a template
    f=~/.ipython/profile_dysh/startup/90-numpy.py
    echo 'import numpy as np'
    echo 'import numpy.ma as ma'
    echo 'import math'
    echo 'import matplotlib.pyplot as plt'
    echo 'import pandas as pd'
    echo 'import dysh'
    echo 'print("dysh is ready")'
fi

**Comment by tchamberlin** [comment]
My implementation does most of the above -- uses a `dysh` profile by default, which will be automatically created for the user whenever they first launch `dysh`. It imports a few sensible-seeming things and alerts the user of what it has done

This definitely still needs some work, but I'm calling this done for now. We will need to review the draft together before merging anything in, though
