### ISSUE TITLE
Fix release-0.2.0

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#109]
A few issues:
- The `release-0.2.0` branch is failing all checks due to `hatch` not being installed
- `requirements_dev.txt` has been removed (by me, as part of the migration to `pip-compile`), which is causing problems somewhere
- pre-commit hooks have not been run on `release-0.2.0`

**Comment by tchamberlin** [comment]
@mpound Is there anything in `main` that shouldn't be a part of `release-0.2.0`? One option would be to merge `main` into `release-0.2.0`; this would pick up the pre-commit changes

Otherwise I can just re-do the same steps I did in `main`, but for `release-0.2.0`

**Comment by mpound** [comment]
A draft PR main->release-0.2.0 shows conflicts but they seem to be mostly due to black formatting.  I don't see any features in main that aren't already in or shouldn't be in release-0.2.0

**Comment by tchamberlin** [comment]
I believe this is fixed by #117
