### ISSUE TITLE
need small test data directory

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#11]
so notebooks can be self contained and integration test scripts will work

**Comment by teuben** [comment]
can we define a few "wget" commands from a designated place, ideally GBT and UMD so we keep them in sync. I don't see many Makefile's in dysh, but they're so self-documenting and good for things like this.

**Comment by teuben** [comment]
equally so, don't we need some environment, e.g. $DYSH_DATA_PATH, that offer some flexibility to using/installing dysh?

**Comment by teuben** [comment]
astropy has the getdata() method, including caching. I'm more thinking of something like

     def getdata_dysh(filename, path=None)

where path can be a colon separated list of directories where it will look for that filename.

Could also hard-code path='/data/gbt'   and/or allow a $PATH which then expands to that $PATH if $PATH is in the environment.
Anything to make it user friendly.

**Comment by astrofle** [comment]
We have the test data directory now, so I'll close this and open a new issue about the data discovery/retrieval functions.
