### ISSUE TITLE
dysh shell initialization fails

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#124]
When trying to run the new dysh command line in RC2, I get a warning about matplotlib backends and then a failure due to use of union symbol in __init__ method signature. 

% pip install dysh==0.2.0rc2
% python --version
Python 3.9.13
% /path/to/anaconda/bin/dysh
Bad value in file 'matplotlibrc', line 38 ('backend      : qt4agg'): Key backend: 'qt4agg' is not a valid value for backend; supported values are ['GTK3Agg', 'GTK3Cairo', 'GTK4Agg', 'GTK4Cairo', 'MacOSX', 'nbAgg', 'QtAgg', 'QtCairo', 'Qt5Agg', 'Qt5Cairo', 'TkAgg', 'TkCairo', 'WebAgg', 'WX', 'WXAgg', 'WXCairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']

Traceback (most recent call last):
  File "/n/lupus/mpound/anaconda3/bin/dysh", line 5, in <module>
    from dysh.shell import main
  File "/n/lupus/mpound/Anaconda3-2022.10/lib/python3.9/site-packages/dysh/shell.py", line 48, in <module>
    def init_shell(colors: str, profile: str | Path, *ipython_args, sdfits_files=None):
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by teuben** [comment]
FYI i did not get this error.  But I did see I got a new profile_dysh, yet this was not reported in my terminal. I think we should report that, under full disclosure of messing with the users' environment.

I used a fresh recent anaconda3 ( python --version -> Python 3.11.5)

**Comment by tchamberlin** [comment]
Yes, I have some Python 3.9-incompatible type annotations. Fixing in #125; WIP

**Comment by tchamberlin** [comment]
Regarding the creation of profile_dysh: this is ipython behavior; I haven't added any code that does this. I'm not even sure how to reliably detect that this directory has been created

**Comment by teuben** [comment]
this did not work for me, despite the advertisement:

        dysh --no-banner

**Comment by tchamberlin** [comment]
What didn't work?

On my end:

```txt
$ dysh --no-banner

In [1]:                                                                                                                                                                                                                                      
Do you really want to exit ([y]/n)?
```

```txt
$ dysh
Python 3.12.0 (main, Nov 19 2023, 21:56:04) [GCC 13.2.1 20231011 (Red Hat 13.2.1-4)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.17.2 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: dysh

--------------------------------------------------------------------------
                         Welcome to Dysh v0.2.0rc2

    Example usage: https://dysh.readthedocs.io/en/latest/example.html
    Bug repots:    https://github.com/GreenBankObservatory/dysh/issues

    For help with a Dysh routine from the command line,
    use the builtin 'help'. e.g.:

        help(GBTFITSLoad)

    The following items have been made globally available for convenience:
        pd (from pandas)
        np (from numpy)
        GBTFITSLoad (from GBTFITSLoad)
        Table (from Table)
        fits (from astropy.io.fits)

   To suppress this banner, start with --no-banner flag
--------------------------------------------------------------------------
```

**Comment by teuben** [comment]
> Regarding the creation of `profile_dysh`: this is ipython behavior; I haven't added any code that does this. I'm not even sure how to reliably detect that this directory has been created

I only discovered later you used a different method for the dysh command, so you can probably ignore my comment.

**Comment by teuben** [comment]
on my end:

dysh --no-banner
Traceback (most recent call last):
  File "/home/teuben/NEMO/redo/nemo/anaconda3/bin/dysh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/teuben/NEMO/redo/nemo/anaconda3/lib/python3.11/site-packages/dysh/shell.py", line 84, in main
    init_shell(colors=args.colors, profile=args.profile, *remaining_args, sdfits_files=sdfits_files)
TypeError: init_shell() got multiple values for argument 'colors'

**Comment by tchamberlin** [comment]
Ah, okay, this is (hopefully) another thing being fixed in #125

**Comment by tchamberlin** [comment]
There are now passing tests for the `dysh.shell` -- if anyone is still having issues, feel free to re-open

**Comment by tchamberlin** [comment]
There are now passing tests for the `dysh.shell` -- if anyone is still having issues, feel free to re-open
