### ISSUE TITLE
help(GBTFITSLoad)  by default does not wrap text

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#126]
We have all these requirements our code doesn't use long lines, but in ipython we do get these long lines which causes sad long lines wrapping and breaking the zen of reading the documentation...

**Comment by mpound** [comment]
Can you give an example?

**Comment by teuben** [comment]
This is not restricted to dysh, it's a help() issue [saw some dicsussions on stackoverflow].

help(astropy.io.fits)  gives :

![image](https://github.com/GreenBankObservatory/dysh/assets/3393049/78d3e069-d35f-484a-a330-82b31ec5595c)

**Comment by tchamberlin** [comment]
Given that our source code is wrapped at 120, I don't think we would have any issues with this? If there are examples from our codebase, then maybe this is worth discussing further

**Comment by teuben** [comment]
I do see a long one in gettp, but as said, this may be an internal ipython issue.

![image](https://github.com/GreenBankObservatory/dysh/assets/3393049/9aeb9811-5465-4abb-bf8b-d07e973a8b81)

**Comment by tchamberlin** [comment]
Ah yes I see -- this is indeed due to a long source line. This should get resolved post-`release-0.2.0`, once we have black and other pre-commit hooks running consistently on everyone's branches
