### ISSUE TITLE
Clean up Python dependencies (wget, Jupyter, Sphinx)

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#139]
### `wget`

[`wget`](https://pypi.org/project/wget/) has been dead since 2015, and gives install warnings on modern python. It is only used in a unit test and in some example code; nothing in the package itself.

Astropy has [a file fetching framework](https://docs.astropy.org/en/stable/utils/data.html#usage-from-outside-astropy) `astropy.utils.data.download_file`, which supports caching, timeouts, etc. We should use this instead, unless there is a reason not to

### Jupyter

Jupyter is **not** a core requirement of "dysh the library": it is not imported anywhere, or otherwise required to run any of the packaged code (notebooks are not included in the Python package). Jupyter _is_ needed to run the examples, and potentially could be considered part of "dysh the app" later on. So, this is an optional req: we should add it to `dysh[all]`, `dysh[dev]`

### Sphinx

Sphinx is not a core requirement of `dysh`, and should be moved to optional dependencies:
- `sphinx`
- `myst-parser`
- `sphinx_inline_tabs`

**Comment by mpound** [comment]
wget is used in the example notebooks now.  I'm fine replacing this with astropy.    I have found distributing notebooks to be a pain point with github.   In another project, I have a separate repo for them, but then one has to be careful to keep them aligned with the current package version.   dysh currently requires people download the notebooks separate or git clone the repo to get them and then install jupyter in their dysh venv. There has to be a better way.

**Comment by teuben** [comment]
Since indeed the astropy caching system is a bit opaque, I'd say we create  a symlink to the dysh specific cashing directory.

**Comment by tchamberlin** [comment]
Done, with the exception of `wget`, which I have left unchanged. See PR #152
