### ISSUE TITLE
Remove unnecessary files from repo

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#140]
The goal here is basically just signal to noise in the repo. There are a variety of files that don't have a clear purpose, which is a bit confusing. Tagging the file authors here -- if any of this needs to stay, just let me know

- Remove Makefiles, autoconf config, etc. Hatch appears to do everything that these would do for us; we should lean into our tooling @teuben 
- the `.env` file is not necessary -- it is only used for local builds of docs right now, but isn't actually required to accomplish this. We might need an `.env` file in the future, for deployment-specific info, but the template only includes config for the docs. This should be purged, and the docs that refer to it should be fixed to simply point to the correct way to run docs (`hatch run docs`) @vcatlett 
- `requirements_dev.txt`: This file isn't needed at all in the current scheme. For simplicity I've set up pip-compile to build all deps (including all optional) into a single `requirements.txt`. See issue (TODO) for more details on this
- `gui/`: The GUI -- at least what is on `main` -- does not currently work out of the box. To be clear, this has nothing to do with whether the GUI should/shouldn't exist, just acknowledging that right now it's not working, and not part of the beta, and it would be cleaner to keep it separate from the core codebase (e.g. a branch or another repo)  @vcatlett 
- `attic/`: Remove this; if we need these files just grab them from an old commit @mpound 
- `fdr`: It's not clear to me why this is in the repo. It doesn't appear to be used or documented anywhere @teuben 

No work is required from anyone else (other than discussion) -- I'll open a PR for this once we agree on course of action

**Comment by tchamberlin** [comment]
Absolutely! I have several branches that implement this in my fork, and I am happy to rebase them onto the updated `main`  and open PRs once #138 is resolved. FWIW, I had no issues merging `release-0.2.0` into `main` on my end; it was just a fast forward.

**Comment by teuben** [comment]
I still don't use hatch, so far for a good reason. It's not a good idea to fully rely on one developers model, there should be an option to use other tools. A Makefile is a great way to give quick hooks into the system, without having to copy and paste complex long commands, let me please review where the Makefile stands in light of the current system before cutting it out.

**Comment by teuben** [comment]
Re. fdr:    (find data recursively) - we may not need if we have a good mechanism to get files, as discussed in #139

**Comment by tchamberlin** [comment]
There is no requirement to use Hatch -- if you would like to use a Make-based system, you are welcome to do so. We could add those to `.gitignore` and you could keep them locally in your repo. But I'd like to keep all of the project config in `pyproject.toml`.

Another note: even while using Hatch, there is no requirement to have it manage your envs for you. I prefer to manage them myself, and it works fine. `hatch run` will respect whatever env you are currently in, so you can e.g.

```sh
python3.9 -m venv /path/to/dysh-env
source /path/to/dysh-env/bin/activate
hatch run docs
```

This will run `sphinx-autobuild` (as configured in `pyproject.toml`)

Final note: `hatch` is not a requirement, but technically `hatchling` is (it is used instead of  `setuptools` due to `[build-system]` in `pyproject.toml`

I have opened PR #150 to address the above. Regarding `fdr`, I've left this alone for now
