### ISSUE TITLE
CI cleanup and enhancements

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#141]
Proposed changes to CI:

- Rename `hatch-and-pytest` to just `ci`. All CI can just go in here as various jobs
- Several workflows aren't used anymore, and should be removed (`build.yml`, `pyinstaller.yml`, `workflow.yml`, `pre-commit.yml`)
- pre-commit should use pre-commit.ci instead of GH Actions. This is e.g. what Astropy uses, and it provides some nice extra features:
  - faster builds
  - where possible, will automatically fix commits that fail the hooks (instead of previous behavior where the build would just fail)
  - automatically submits PRs to update hook versions on a weekly basis
- Enable code coverage during tests. Currently we aren't calculating or tracking coverage at all; I think it would be good to at least be keeping track of it. No need to enforce any specific level of coverage at this point though
- Don't indicate an `environment` in the CI workflow; this is what is causing the "temporarily deployed to hatch build" spam in our PRs

I have code to accomplish all of the above, this issue is just for discussion

**Comment by mpound** [comment]
workflow.yml was my initial test to get the workflow_dispatch: tag working so that we could click Run to manually run a workflow.  Since we now know how to do it and use it  elsewhere, this file can be removed.

**Comment by tchamberlin** [comment]
I have opened #151 which addresses all of the above (but is based on the #150, so isn't quite ready for review)
