### ISSUE TITLE
Azimuth values in GBTFITSLoad.summary()

### ISSUE THREAD

**Issue by dbautista98** [GreenBankObservatory/dysh#148]
When printing the observation summary with `GBTFITSLoad.summary()` the azimuth values for an observation are different in GBTIDL and dysh. In GBTIDL the Az is 352.2 and 187.2 but with dysh, it is 262.88 and 268.9

Here is the output with GBTIDL 
![gbtidl](https://github.com/GreenBankObservatory/dysh/assets/60448615/3cd72b76-f150-4737-8713-e696c0cc21f8)

Here is the output with dysh
<img width="1008" alt="dysh" src="https://github.com/GreenBankObservatory/dysh/assets/60448615/9f04e45c-589a-4f51-b2db-901992bbeff0">

**Comment by astrofle** [comment]
Hi Daniel,
Thanks for opening up this issue.
`dysh` takes the mean of the azimuth and elevation when producing the summary, while `GBTIDL` reports the first value for the scan. 
We will document this better so it is clear. Would that be a proper solution from your perspective?

**Comment by dbautista98** [comment]
Got it, thanks for the clarification! Yes that sounds like a good solution.

**Comment by mpound** [comment]
To clarify, the average is taken for columns VELOCITY, RESTFREQ, DOPFREQ, AZIMUTH, ELEVATIO.
