### ISSUE TITLE
Subbeamnod routine cannot access plnum

### ISSUE THREAD

**Issue by jfrothingham** [GreenBankObservatory/dysh#153]
Unable to retrieve a subbeamnod scan because of apparent problems accessing 'plnum'

I've been following the SubBeamNod example (https://dysh.readthedocs.io/en/latest/examples/subbeamnod.html) with a different dataset.

I am using dysh-0.2.0b with Python3.11 on a computer that I think is running RedHat 8. (Thales data reduction machine)
Data is located at /home/scratch/jfrothin/testdata/AGBT19B_096_08.raw.vegas in the Green Bank filesystem.

Here is a screenshot of the error I'm seeing. I get this error regardless of whether I specify kwargs or not, and regardless of which scan I use.

![image](https://github.com/GreenBankObservatory/dysh/assets/16109523/d00c6584-9503-4042-84e8-46fe638556cf)

However, sdfits.summary() shows that this scan does have values for PLNUM and FDNUM.

![image](https://github.com/GreenBankObservatory/dysh/assets/16109523/4d442a25-8714-4f30-8744-97926e50c50f)

**Comment by tchamberlin** [comment]
We will need to reproduce the error somehow -- is the dataset you are using something that we could test against?

**Comment by jfrothingham** [comment]
Yes, I think you can test against it. It's a dataset we were considering using as a training example

**Comment by tchamberlin** [comment]
I can reproduce this:

```py
sdfits = GBTFITSLoad("/home/scratch/jfrothin/testdata/AGBT19B_096_08.raw.vegas")
sbn = sdfits.subbeamnod(scan=18, fdnum=0, plnum=1)
```

Indeed, `plnum` is not defined, since `rx` is not `"Rcvr26_40"`. But upon fixing that, I get

```
File <snip>/dysh/spectra/scan.py:228, in TPScan.__init__(self, gbtfits, scan, sigstate, calstate, scanrows, calrows, bintable, calibrate)
    225 # print("BINTABLE = ", bintable)
    226 # @TODO deal with data that crosses bintables
    227 if bintable is None:
--> 228     self._bintable_index = self._sdfits._find_bintable_and_row(self._scanrows[0])[0]
    229 else:
    230     self._bintable_index = bintable

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by tchamberlin** [comment]
After fixing the `plnum` bug (see [153-subbeamnod-routine-cannot-access-plnum](https://github.com/GreenBankObservatory/dysh/tree/153-subbeamnod-routine-cannot-access-plnum))

It appears that this causes an error:

```py
sdfits = GBTFITSLoad("/home/scratch/jfrothin/testdata/AGBT19B_096_08.raw.vegas")
sbn = sdfits.subbeamnod(scan=18, fdnum=0, plnum=1)
```

But this does not:
```py
sdfits = GBTFITSLoad("/home/scratch/jfrothin/testdata/AGBT19B_096_08.raw.vegas/AGBT19B_096_08.raw.vegas.A.fits")
sbn = sdfits.subbeamnod(scan=18, fdnum=0, plnum=1)
```
The difference being that the former (the path in the original issue) is the path to the SDFITS folder, while the latter is the specific path of a specific bank (as per [the example](https://dysh.readthedocs.io/en/latest/examples/subbeamnod.html)). 

@mpound Should both of these paths work? i.e. is giving the SDFITS folder path a supported operation?

**Comment by jfrothingham** [comment]
I should have attached screenshots of my full code, sorry. I ran dysh from within the folder "/home/scratch/jfrothin/testdata/AGBT19B_096_08.raw.vegas" and did specify the path of the bank:

```
filename='AGBT19B_096_08.raw.vegas.A.fits'
sdfits = GBTFITSLoad(filename)
sbn = sdfits.subbeamnod(scan=18, fdnum=0, plnum=1)
```
This code produced the error I reported here.

**Comment by jfrothingham** [comment]
I'm still encountering the issue, but I think that's due to installation problems on my end rather than anything to do with this bug.

**Comment by astrofle** [comment]
> After fixing the `plnum` bug (see [153-subbeamnod-routine-cannot-access-plnum](https://github.com/GreenBankObservatory/dysh/compare/release-0.2.0...153-subbeamnod-routine-cannot-access-plnum))
> 
> It appears that this causes an error:
> 
> ```python
> sdfits = GBTFITSLoad("/home/scratch/jfrothin/testdata/AGBT19B_096_08.raw.vegas")
> sbn = sdfits.subbeamnod(scan=18, fdnum=0, plnum=1)
> ```
> 
> But this does not:
> 
> ```python
> sdfits = GBTFITSLoad("/home/scratch/jfrothin/testdata/AGBT19B_096_08.raw.vegas/AGBT19B_096_08.raw.vegas.A.fits")
> sbn = sdfits.subbeamnod(scan=18, fdnum=0, plnum=1)
> ```
> 
> The difference being that the former (the path in the original issue) is the path to the SDFITS folder, while the latter is the specific path of a specific bank (as per [the example](https://dysh.readthedocs.io/en/latest/examples/subbeamnod.html)).
> 
> @mpound Should both of these paths work? i.e. is giving the SDFITS folder path a supported operation?

@tchamberlin yes. `dysh` should be able to load multiple fits files in a directory. This feature was introduced as part of 0.2.0. (Thanks for looking into this issue.)

**Comment by astrofle** [comment]
@jfrothingham I had to uninstall `dysh` and then reinstall using the command Thomas provided for this to work. Here's what I did (from the `Python` environment with `dysh`):
```
pip uninstall dysh
pip install git+https://github.com/GreenBankObservatory/dysh.git@153-subbeamnod-routine-cannot-access-plnum
```
Hope this helps.

**Comment by tchamberlin** [comment]
Ah right! You can do it in one command via the `-I`/`--ignore-installed` flag:

```sh
pip install -I git+https://github.com/GreenBankObservatory/dysh.git@153-subbeamnod-routine-cannot-access-plnum
```

**Comment by mpound** [comment]
Late to this party, but I do think there is still a potential bug in subbeamnod having to do with the receiver assumption  Rcvr26_40, which I got from the GBTIDL implementation.  I will work with Pedro to improve my understanding of which Rxs have or historically had polarization capability.

**Comment by astrofle** [comment]
@mpound currently, only Argus (the 3 mm 16 feed receiver being used for the [GBT EDGE](https://greenbankobservatory.org/science/gbt-surveys/edge/) survey) has single polarization capabilities. For observations with every other receiver the data should have at least two polarizations. The `if else` clause in [`dysh.fits.GBTFITSLoad.subbeamnod`](https://github.com/GreenBankObservatory/dysh/blob/99e826c3e63693e0d8837feff44ba2adc239d2e1/src/dysh/fits/gbtfitsload.py#L743) is there because the Ka receiver (Rcvr26_40) has had its feeds mislabelled for some time now. So, if you want to calibrate the data properly for that particular receiver you have to swap the polarization and feed values. For the rest of the receivers the method should use the same polarization for the selected feeds. I hope that clears a bit the confusion.

Apologies for not explaining that earlier.

PS. There is an open item to fix the mislabelling of the Ka receiver feeds. That is also why there is a [commented part](https://github.com/GreenBankObservatory/dysh/blob/99e826c3e63693e0d8837feff44ba2adc239d2e1/src/dysh/fits/gbtfitsload.py#L794C24-L794C33) of the `else` clause referring to the date of the observations. For observations taken after the Ka beam mislabelling issue is fixed the polarizations should not be swapped.
