### ISSUE TITLE
Fix undefined variables

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#155]
Similar to #153, there are a few more undefined variables that show up in linting. I'm not sure that all of these are in live code paths, but it would be good to resolve them regardless. And, unlike most of the linting errors, I can't unambiguously fix them myself.

`sys` is undefined (just need to `import sys`)

https://github.com/GreenBankObservatory/dysh/blob/4e52824f258e2119b1f04fc7cf893ae0bfbe1e4d/src/dysh/util/core.py#L79

`pair` is undefined -- perhaps this should be `b`?

https://github.com/GreenBankObservatory/dysh/blob/4e52824f258e2119b1f04fc7cf893ae0bfbe1e4d/src/dysh/spectra/core.py#L116-L118

`SpectrumList` is undefined:

https://github.com/GreenBankObservatory/dysh/blob/4e52824f258e2119b1f04fc7cf893ae0bfbe1e4d/src/dysh/fits/sdfitsload.py#L173

`dowcs` is undefined (maybe this was supposed to be set as `self.dowcs` in `load()`?):
https://github.com/GreenBankObservatory/dysh/blob/4e52824f258e2119b1f04fc7cf893ae0bfbe1e4d/src/dysh/fits/sdfitsload.py#L180

Again here:
https://github.com/GreenBankObservatory/dysh/blob/4e52824f258e2119b1f04fc7cf893ae0bfbe1e4d/src/dysh/fits/sdfitsload.py#L210

**Comment by mpound** [comment]
The ones in sdfitsload.py are in the method _loadlists() which I have mentally deprecated since it was leftover from performance testing.   I only left it in because it was being called from the GUI.  @vcatlett Can I remove _loadlists()?

**Comment by mpound** [comment]
This was fixed in PR #178 (or possibly earlier)
