### ISSUE TITLE
Sequence diagram of GBTIDL plotter workflow

### ISSUE THREAD

**Issue by vcatlett** [GreenBankObservatory/dysh#169]
Or just a screen recording. Something that makes the plotter UI requirements clear.

**Comment by teuben** [comment]
do we have a requirement that there could be more than one plotter on the screen?   (great for comparing spectra)

**Comment by astrofle** [comment]
We produced a recording of how the GBTIDL plotter works. The recording can be found [here](https://drive.google.com/file/d/1uQc22SxW03gbuqROtHrYa1j-I1jjFF3U/view).
