### ISSUE TITLE
Need a spectrum import method

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#175]
**Feature description**
I have an ascii spectrum, and wanted to use dysh for some baseline subtraction and maybe make some nice annotated plots, but there wasn't a good way to do it.  I can probably do it in astropy, but dysh ought to give common 3rd party formats (ascii spectrum and a FITS primary HDU spectrum) an easy buy-in.

**Solution**
Some Spectrum.read() method, even though it's not on our horizon.

**Additional context**
I did this in NEMO , and even though it's 3 lines of bash code (5 if you plot), you really don't wanna know how I did it.

**Comment by mpound** [comment]
This is completed in main with Spectrum.read
