### ISSUE TITLE
Determine where galactic center frequencies for the LO system come from

### ISSUE THREAD

**Issue by vcatlett** [GreenBankObservatory/dysh#177]

**Comment by astrofle** [comment]
From `gbt/devices/IF/LO1/LO1Coordinator/Coordinator/LO1Coordinator.cc`

```C
    // Standard solar motion (from Methods of Experimental Physics, ed Meeks,
    // vol 12, part C, sec 6.1.5.2, p281):
    // 20 km/s towards RA 18h Dec +30d (1900).
    // (expressed here as a J2000 vector)
    static const float lsrk[3] = {0.29000f, -17.31726f, 10.00141f};

    // Peculiar solar motion from Delhaye 1965: in Galactic Cartesian
    // coordinates (+9,+12,+7) km/s.  This corresponds to about 16.6 km/s
    // towards Galactic coordinates L2 = 53 deg, B2 = +25 deg, or RA,Dec
    // 17 49 58.7 +28 07 04 J2000.
    static const float lsrd[3] = {-0.63823f, -14.58542f, 7.80116f};

    // Reference: IAU trans 1976, 168, p201.
    // Solar velocity due to galactic rotation and translation
    // speed = 300 km/s
    // apex  = l2,b2  90deg, 0deg
    //  = RA,dec  21 12 01.1  +48 19 47  J2000.0
    static const float local_group[3] = {148.23284f, -133.44888f, 224.09467f};

    // LSRK velocity due to Galactic rotation
    // Speed = 220 km/s toward
    // RA,Dec  21 12 01.1  +48 19 47  J2000.0
    // Galactic-Barycentric motion is given as:
    // 232.280km/sec toward  20:55:26.7, 47:49:23.5(J2000)
    static const float galactocentricVel[3] =
                         { (float)108.065250,
                           (float)-112.448524,
                           (float)172.137240};

    // Cosmic Microwave Background.
    // Reference: GBT LO Doppler Corrections, R. Fisher, June 2000.
    // 369.5 km/s toward (11:12:56.43, -6:57:50.0)J2000
    // static const float cmb[3] = {360.341291f, -75.048700f, 32.436035f};
    static const float cmb[3] = {-359.069130f, 74.783745f, -44.799569f};

```

Note that for the LSRD [Delhaye 1965](https://ui.adsabs.harvard.edu/link_gateway/1965gast.book...61D/ADS_PDF) gives the components as (-9,+12,+7) km/s (page 73 of the book, 13 of the pdf).

**Comment by mpound** [comment]
GBTIDL's implementation is a bit different (gbtild/pro/toolbox/chdoppler.pro):

- LSRK : same as above, which is the same as astropy. 
- LSRD :  "16.6 KM/S toward RA=17:49:58.7 hours, DEC=28.07.04 DEG IN 2000 EPOCH COORDS"
             - different than astropy because of rounding to nearest 0.1 km/s https://docs.astropy.org/en/latest/api/astropy.coordinates.LSRD.html#
- Galactocentric: "LSRD + 220 km/s towards RA=21:12:01.1 DEC=48.19.47 in J2000 Epoch"
            - quite different than astropy https://docs.astropy.org/en/latest/api/astropy.coordinates.Galactocentric.html#galactocentric

Based on slack conversations, we will use astropy definitions and document the difference.

**Comment by astrofle** [comment]
Lastly, Frank's documentation on the definitions being used: https://www.gb.nrao.edu/~fghigo/gbtdoc/doppler.html
