### ISSUE TITLE
implement write method on GBTFITSLoad

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#19]
a special write method that will allow scan number input.  different from SDFITSLoad.write(rows=)
e.g. write_scan(file,scans=[],....)

**Comment by mpound** [comment]
bug fix commit e62e574942e53c0778e18e5a4765fc517abc0b4a , now can read back in what it wrote out!

**Comment by astrofle** [comment]
This seems to be working fine, and the outputs are compatible with the [`gbtgridder`](https://github.com/GreenBankObservatory/gbtgridder/tree/release_2.0). 
I have not tested if the metadata is updated properly, though that can be verified at a later stage.
