### ISSUE TITLE
implement write method on Spectrum

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#20]
write a single spectrum to a file, file format TBD

**Comment by mpound** [comment]
implemented in mwp-devel

**Comment by astrofle** [comment]
This works, but the output file is not an SDFITS.
I'll close this for now, but down the line it would be useful to be able to write this to SDFITS, and other, formats.

**Comment by mpound** [comment]
please open an RFE for FITS output so it doesn't fall trhough the cracks.
