### ISSUE TITLE
ACS test data does not include documentation how gbtidl spectrum was produced

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#220]
**Feature description**
In testdata/AGBT05B_047_01/gbtidl, how the getps spectrum was produced is not documented (see e.g., testdata/gbtidl_spectra/README.md) .  This makes it difficult to ensure that dysh is doing the same thing. 

**Solution**
If you have an idea of how to solve the problem, please describe it!

**Additional context**
I have circumvented the assert in test_gbtfitsload.py: test_getps_ac() until this gets sorted out.

**Comment by astrofle** [comment]
You can find the script used to produce that data here: https://github.com/astrofle/dysh-at/blob/main/gbtidl/get_onoff.pro
Lines 29 through 42. It is using `getps` on scan 52 of [AGBT05B_047_01.raw.acs.fits](https://github.com/GreenBankObservatory/dysh/blob/main/testdata/AGBT05B_047_01/AGBT05B_047_01.raw.acs/AGBT05B_047_01.raw.acs.fits).
The test works fine in main, so the problem must have been introduced by the changes on the `q4_selection_application` branch.

**Comment by mpound** [comment]
Thanks.  I changed how averaging works in ScanBlock so that is surely the genesis of the error, it is just a matter of hunting it down.
