### ISSUE TITLE
Can't have xaxis unit as channels in SpectrumPlot

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#229]
**Feature description**
Plotting a spectrum by channel number

**Solution**
Need to peel off special case of _xaxis_unit='chan'_ in plot.

**Additional context**
The reason this fails is because there is no "channel" astropy Quantity, so we need to circumvent the conversion from Spectral units to the request xaxis_unit

**Comment by astrofle** [comment]
Would defining a `"chan"` unit help? See e.g., https://docs.astropy.org/en/stable/units/combining_and_defining.html#defining-units

**Comment by mpound** [comment]
That is a good idea, have to figure out how equivalencies() work with that.    We already have defined "mmHg" because it is not standard but in our FITS files.

**Comment by mpound** [comment]
This is now fixed in release-0.3.0 and main.
