### ISSUE TITLE
shifting spectrum for getfs() needs to be more accurate

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#235]
**Describe the bug**
In the current getfs() the difference between dysh and gbtidl is ~20mK (for a spectrum with RMS ~500 mk). This is due to the spectrum shift routine uses scipy.ndimage.shift() based on spline functions.  gbtidl has this option too, but still shows small differences.  Ideally we would reproduce the FFT based shifter/

**How to Reproduce**
The pytest in test_scan.py documents we use a level of 0.02, whereas ideally we would like to get to 1e-5 or so.

**Environment**
- Dysh version
- Python version
- OS

**Comment by astrofle** [comment]
This should be solved by #280.
