### ISSUE TITLE
Division of Spectrum uses wrong method

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#241]
**Describe the bug**
In spectra/spectrum.py the division operator method is __div__.  This must be __truediv__ in Python 3.  Changing it to __truediv__ causes other errors in our notebooks, so it is not just simple substitution. 

**How to Reproduce**
spectrum1 / spectrum2 

**Environment**
- Dysh version 0.2.x
- Python version 3.9
- OS Ubuntu 24

**Comment by astrofle** [comment]
Closing as it seems to have been solved.
