### ISSUE TITLE
Breaking data out of dysh

### ISSUE THREAD

**Issue by leemundy** [GreenBankObservatory/dysh#250]
**Feature description**
What problem are you trying to solve that you currently can't?
Getting the frequency/velocity axis written into an astropy units object with my selection of units;
km/s in choice of reference frame, Hz, GHz, channel number etc. This can already be done for the
"y-axis" (flux).

**Solution**
If you have an idea of how to solve the problem, please describe it!

**Additional context**
The top level goal is to give the user their spectrum as arrays x and y that they can export from python
or use for whatever purpose in python.

**Comment by leemundy** [comment]
Hi,

  If the person is familiar with python, this might mean creating local
variables with the spectra of interest, putting them
into their own dictionary(s) and writing out a pickle file. I agree that it
could also be an ascii file or FITS file. I would
argue that FITS is the least likely of the person just wants a spectrum to
be read into some modeling program,
or to put into another python notebook that makes a combined display of
various images and spectra -- for
publication.

Lee

**Comment by mpound** [comment]
This is related to milestone "integrated read/write for SDFITS, Spectrum, ScanBlock" for the current quarter.

**Comment by mpound** [comment]
This development now completed in the main branch.  You can save data from a Spectrum as ASCII of various flavors or FITS.  Also can save Scan/ScanBlock as SDFITS.  Also can subselect data from an SDFITS file and write it to a new SDFITS file.
