### ISSUE TITLE
Wildcard in channel selections for spectra

### ISSUE THREAD

**Issue by leemundy** [GreenBankObservatory/dysh#251]
**Feature description**
In a command like:
ta.baseline(degree=2,exclude=[(1000,3000),(5000,7000),(8500,11000)],remove=True)
You do not quickly know the first or last point in a spectrum so it would be more
convenient if there was a wildcard ability. For example,
ta.baseline(degree=2,exclude=[(*,3000),(5000,7000),(8500,*)],remove=True)
ta.baseline(degree=2,exclude=[(,3000),(5000,7000),(8500,)],remove=True)
Perhaps this exists but I do not know what to put to indicate -- take all channel
beyond or below a number.

**Solution**
If you have an idea of how to solve the problem, please describe it!

**Additional context**
Simplies user interaction, especially in frequency switched spectra where the area of most interest
is just the overlap region between the two negative images.

**Comment by teuben** [comment]
an include= was added to our Spectrum.baseline which turns an include= into exclude= and passes this on to the next baseline routine. However,  for now this only works in channel space, since attaching units to baseline selection is broken,
