### ISSUE TITLE
Descriptive error/warning message for blank integrations

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#254]
**Describe the bug**
There's a warning issued when one integration is blanked. This is confusing as there is no additional context given to the users.

**How to Reproduce**
```Python
# The data lives in the GBO filesystem.
sdf = GBTFITSLoad("/home/sdfits/TRFI_092523_L1/TRFI_092523_L1.raw.vegas/")
tpscan = sdf.gettp(scan=1, ifnum=0, plnum=0)
  /home/sandboxes/psalas/Dysh/dysh/src/dysh/spectra/core.py:354: RuntimeWarning: Mean of empty slice
  meandiff = np.nanmean(calon[chrng] - caloff[chrng])
```

**Environment**
- Dysh version 0.3b
- Python version 3.11
- OS RedHat 8

**Comment by mpound** [comment]
See also my comment on #313

**Comment by jfrothingham** [comment]
+1 and a request for the option to suppress this output. In reducing a moderately-sized dataset, my code calls `getps()` several hundred times (50 scans x 8 IFs x 2 polarizations). This warning is printed every time. 

The following code still produces the warning. Dysh version 0.3.0, run with `/home/dysh/release/stable/bin/dysh-lab` on a GBO data reduction machine.

`import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter("ignore")
remsdfits.getps(scan=7, ifnum=2, plnum=0)`
