### ISSUE TITLE
Latest version of pandas.Series does not have an append method.

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#27]
The latest version of pandas ([2.0.2](https://pandas.pydata.org/docs/)) does not have a `pandas.Series.append` method.
We should either require an appropriate version of pandas or use something other than append to achieve the same functionality.

This affects things like:
https://github.com/GreenBankObservatory/dysh/blob/9062ff3eb81a75fbb460a51a75eaba3675ed0236/src/dysh/fits/gbtfitsload.py#L133

**Comment by mpound** [comment]
Great minds....I replaced many of these yesterday with pandas.concat() which is the recommended replacement.  I see there are a couple more.  I will get these too.

**Comment by mpound** [comment]
fixed in mwp-devel
