### ISSUE TITLE
Differences in system temperature between GBTIDL and dysh

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#28]
GBTIDL and dysh produce different values of the system temperature. Here is the notebook showing the on-going investigation:
<a href="https://github.com/GreenBankObservatory/dysh/blob/pedro-devel/notebooks/getps_dysh_vs_gbtidl.ipynb">link to notebook</a>.

**Comment by astrofle** [comment]
The difference comes from IDL using inclusive ranges and python exclusive. Adding one channel when computing the system temperature solves the issue.

**Comment by mpound** [comment]
Wow, so this on the 10% edge exclusion?

**Comment by astrofle** [comment]
This is now working on single integrations. This issue does not cover time averaging.
