### ISSUE TITLE
PyPI version is not the latest main branch

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#3]
When installing from PyPI (`pip install dysh`) the version installed is not the same as the main branch. This leads to a `NameError` error when trying to load GBT SDFITS files. Example:

```
from dysh.fits.gbtfitsload import GBTFITSLoad
f = "/home/scratch/psalas/support/UMD-py/examples/onoff-L/data/TGBT21A_501_11.raw.vegas.fits"
p = GBTFITSLoad(f)
```

This bug is already fixed in the main branch, but I thought I'd post this here in case someone else wanted to move past this. To install the main branch follow the [README](https://github.com/GreenBankObservatory/dysh#development) ignoring the part where it says to install hatch (so, clone and `pip install -e .`) .

**Comment by tchamberlin** [comment]
pip actually provides native support for installing from git, so you can avoid the cloning step:

```bash
# Install from latest commit on default (main) branch
pip install git+https://github.com/GreenBankObservatory/dysh
```

You can also install from a specific commit:

```bash
# Install from commit with given hash
pip install git+https://github.com/GreenBankObservatory/dysh@41551df5a4edc951b209e150958a750dab677b27
```

Full documentation here (tags, branches, etc. are also supported): https://pip.pypa.io/en/stable/topics/vcs-support/

This could perhaps be added to the README, similar [astroquery](https://github.com/astropy/astroquery):

> To install the 'bleeding edge' version:
> ```
> $ pip install git+https://github.com/astropy/astroquery.git
> ```

**Comment by mpound** [comment]
pypi now matches release-0.1.0
