### ISSUE TITLE
Smooth functionailty not working for me

### ISSUE THREAD

**Issue by karenloneil** [GreenBankObservatory/dysh#302]
The smooth routine does not seem to work for me.  I tried it, following the recipe given in: https://github.com/GreenBankObservatory/dysh/blob/main/notebooks/examples/smoothing.ipynb

when I run it, I get errors along the lines of:
TypeError: Spectrum.smooth() takes 1 positional argument but 3 were given

**Comment by teuben** [comment]
can you check what your spectrum smooth helper does, e.g.

help(sp1.smooth)

I wonder if you have the 0.3.0 that doesn't have the new smooth in it

**Comment by karenloneil** [comment]
Help on method smooth in module dysh.spectra.spectrum:

smooth() method of dysh.spectra.spectrum.Spectrum instance

**Comment by teuben** [comment]
this is a 0.3 release, which still has the stub for smooth. Unless you want to hack and do git branching, you won't see the full smooth I showed today.  It was that CAVEAT Im afraid.

**Comment by karenloneil** [comment]
Got it. I found it in the documentation link that Kirstin sent.

Karen
