### ISSUE TITLE
Documentation or code error for vel frame

### ISSUE THREAD

**Issue by karenloneil** [GreenBankObservatory/dysh#303]
The online documentation on velocity reference frames states that the data is shown in the velocity frame of the sdfits files.   I have data taken in the optical, lsrk reference frame, and this is noted in the sdfits header , but it is not.  Dataset is lsr, but the plot shows topo reference frame.  I can readily switch to lsrk mode, but that is not the default

**Comment by mpound** [comment]
Can you provide the data file (or a few integrations from it) so we can look into this issue?

**Comment by karenloneil** [comment]
sure.  any spectral line scans from AGBT22B_065

**Comment by mpound** [comment]
This appears to be an case of 1) imprecise documentation and 2) non-optimal default behavior.   I'll address these in turn.

1) The documentation referred to is in the [velocity frames example notebook](https://github.com/GreenBankObservatory/dysh/blob/main/notebooks/examples/velocity_frames.ipynb) where it says (cell 23) "The default plot uses the velocity frame and convention found in the SDFITS File." More accurate would be, "The default plot uses the frequency frame and Doppler convention found in the SDFITS file."   In GBT SDFITS, CTYPE1 is always "FREQ-OBS" meaning topocentric frequency in Hz.  For these data VELFRAME is "OPTI-LSR".  So in this case, the default x-axis of the plot is topocentric frequency and the optical convention, $\nu_{opt}$, in Hz.   
2) Assuming $s$ is the spectrum, $s.plot(xaxis\\_unit='km/s')$  currentply plots topocentric velocity using the optical convention and km/s.   More astronomer-friendly behavior would be instead to plot in the velocity frame specified by VELFRAME when a velocity unit is specified in the arguments, in this case LSRK using the optical convention.
