### ISSUE TITLE
WCS wrong after a smoothed spectrum is indexed

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#307]
**Describe the bug**
After smooth (which decimates) and indexing a spectrum, the WCS is wrong.

**How to Reproduce**
ta2 = ta.smooth('box',128)
ta3 = ta2[30:40]

here ta2 looks ok, but the WCS object is not, but the freq axis is ok, and that is what ta2.plot() is using.

but in ta3 the WCS was updated with the old WCS from ta (the raw data).   This is my own fault, there is an "@todo fix wcs" in the code :-)

**Environment**
- Dysh version - main
- Python version - any
- OS - any

**Comment by teuben** [comment]
There's another place where the WCS is present, in meta.  That's the original one from the raw SDFITS file. We thus have the  WCS in 3 locations. Dangerous.

**Comment by mpound** [comment]
Related to #373?
