### ISSUE TITLE
`getfs` does not respect `scan` selection

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#315]
**Describe the bug**
When using `getfs` and the keyword `scan`, the resulting `ScanBlock` still contains all the available scans irrespective of the scan selection.

**How to Reproduce**
```Python
from dysh.fits import GBTFITSLoad
filename = "/home/dysh/example_data/frequencyswitch/data/TREG_050627/TREG_050627.raw.acs/"
sdf_fs = GBTFITSLoad(filename)
fs_scan = sdf_fs.getfs(scan=90, ifnum=0, plnum=0)
print(f"Number of FS scans: {len(fs_scan)}")
    Number of FS scans: 5
```
It should be 1.

**Environment**
- Dysh version 0.3.0
- Python version 3.11.9
- OS RedHat 7

**Comment by teuben** [comment]
confirmed, I'll look into this.

**Comment by mpound** [comment]
don't forget to fix the bogus pytest on FS selection when this is fixed.
