### ISSUE TITLE
Example notebooks use improper headers

### ISSUE THREAD

**Issue by vcatlett** [GreenBankObservatory/dysh#334]
**Description**
The `.ipynb` files in `dysh/notebooks/examples/` do not use a proper markdown header hierarchy, which causes the documentation builds to create innacurate tables of contents. 

**How to Reproduce**
See the table of contents shown here: https://dysh.readthedocs.io/en/cat-docs-devel/examples/index.html
![image](https://github.com/user-attachments/assets/7be3226d-0c92-4cf2-abc4-e87f2ca58396)
The second entry is "1. Reading and Writing Individual Spectra" when it should be "Frequency-switched Data Reduction." This is because in `dataio.ipynb`, sub-sections of the notebook have titles with only 1 pound sign defining them, making Sphinx think that they need to be included in the table of contents.

**Comment by vcatlett** [comment]
The core Table of Contents issue is fixed by PR https://github.com/GreenBankObservatory/dysh/pull/331

However, I am leaving this bug open until:
- Notebook authors go through their notebooks to make sure the header hierarchy matches what they want to convey
- We add a unit test to make sure future notebooks have exactly one top-level header

**Comment by astrofle** [comment]
I had suggested updated notebook headers in #268, for the notebooks: positionswitch, subbeamnod and multiplefiles (new notebook). Some of the changes were to keep one level 1 heading, and to homogenize the headers between notebooks.

**Comment by astrofle** [comment]
After #367 I think we can close this. @vcatlett if you agree, please go ahead and close.
