### ISSUE TITLE
Notebook download outputs have white background in dark mode

### ISSUE THREAD

**Issue by vcatlett** [GreenBankObservatory/dysh#336]
**Describe the bug**
In the notebooks rendered in the docs, the output from cells that download data via `dysh.util.download.from_url` have a white background in dark mode. 

**How to Reproduce**
See this page in dark mode: https://dysh.readthedocs.io/en/cat-docs-devel/examples/frequencyswitch.html#first-we-download-the-example-sdfits-data-if-necessary
![image](https://github.com/user-attachments/assets/5ac07a1e-c39b-470a-b278-3934b9cd8011)

**Comment by astrofle** [comment]
This is the default behavior for widgets. See for example: https://myst-nb.readthedocs.io/en/latest/render/interactive.html
