### ISSUE TITLE
implement gettp

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#34]
some version of get and calibrate a single total power scan, like GBTIDL gettp is needed.

**Comment by mpound** [comment]
done in mwp-devel

**Comment by mpound** [comment]
I actually agree with this and will make those the defaults.   I had initially misunderstood these arguments in GBTIDL's gettp.

**Comment by mpound** [comment]
they both default to None now.   merged to release-0.1.0.  I will write a test for TPScan.

**Comment by mpound** [comment]
the S/N in dysh is higher than in gbtidl.  I suspect there is a similar weighting/cycle issue as with gbtidl.    I did notice that total power scan is not actually on the Q1 list.

**Comment by mpound** [comment]
GBTIDL scan 152 total power:
![gbtidl_tp152](https://github.com/GreenBankObservatory/dysh/assets/22331890/29a54c5a-8f79-4f2a-aea8-daa087850857)
Dysh scan 152 total power:
![dysh_tp152](https://github.com/GreenBankObservatory/dysh/assets/22331890/51a0768d-b942-43e9-bb64-31c449bfad8b)

**Comment by astrofle** [comment]
I get the same answer when comparing against the patched version of `GBTIDL`. Closing this for now.
