### ISSUE TITLE
add redshift z as a velocity frame

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#344]
**Feature description**
Requested by @teuben a while back.  Making a note of it so it isn't lost.  Would like to have option of changing spectral axis to redshift `z`.   Astropy has some related utility in the `units` module:  https://docs.astropy.org/en/stable/api/astropy.units.equivalencies.doppler_redshift.html
And specutils supports redshift in the Spectrum1D constructor
https://specutils.readthedocs.io/en/stable/api/specutils.Spectrum1D.html#specutils.Spectrum1D.redshift

Science case is any high-z work.

**Comment by astrofle** [comment]
Original issue: https://github.com/GreenBankObservatory/dysh/issues/291

**Comment by mpound** [comment]
I didn't realize he had already submitted it.
