### ISSUE TITLE
GBTFITSLoad().write with multifile=True did not work with multibeam KPFA data?

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#362]
**Describe the bug**
I wanted to write one smaller combined sdfits file from a multibeam data with many scans, but with multifile=True I still got 7 files, one for each beam of the KPFA data.

**How to Reproduce**
```
sdf2 = GBTFITSLoad("nod-KFPA/data/TGBT22A_503_02.raw.vegas")       # from example data
sdf2.write('junk62.fits',scan=[62,63])       # gives 7 files (junk620, junk621 etc.)
sdf2.write('junk62m.fits',scan=[62,63],multifile=True)      # also gives 7 files, but 1 was expected
```
**Environment**
- Dysh version  0.3.0
- Python version 3.11.7
- OS  ubuntu 22

**Comment by teuben** [comment]
Checksum on the two styles are identical, if that even matters.

**Comment by astrofle** [comment]
Shouldn't `multifile=False` give only one file?

**Comment by teuben** [comment]
now that I do have one sdfits file, I still think the user could be warned that each SDFITS file is now in a different extension. this threw me off to for a moment. Here's my suggested change, @mpound 

```
multifile: bool, optional
    If True, write to multiple files if and only if there are multiple SDFITS files in this GBTFITSLoad.
    Otherwise, write to a single SDFITS file, but in different BINTABLE extensions.
```

**Comment by teuben** [comment]
ugh. THe single file multi-bintable file doesn't seem to work:

```
GBTFITSLoad('junk620.fits').gettp(scan=62, ifnum=0, plnum=0)[0]._index[k][:1]
GBTFITSLoad('junk621.fits').gettp(scan=62, ifnum=0, plnum=0)[0]._index[k][:1]

vs.
GBTFITSLoad('junk62.fits').gettp(scan=62, ifnum=0, plnum=0, hdu=1)[0]._index[k][:1]
GBTFITSLoad('junk62.fits').gettp(scan=62, ifnum=0, plnum=0, hdu=2)[0]._index[k][:1]
```

the last two give the same answer (FEED=2), where the first two give FEED=2 and FEED=4

**Comment by mpound** [comment]
1.  Are they written to different bintables in the same HDU if multifile=False?   There should only be multiple bintable extensions on output if there were multiple ones on input.  (see SDF["bintable").    Otherwise I would expect one giant bintable
2.  hdu isn't a valid keyword for the calibration routines, only for SDFITSLoad/GBTFITSLoad construction.

**Comment by mpound** [comment]
Hmmm....I see that HDU is added as a keyword by the GBTFITSLoad constructor, so gettp(hdu=N) should do something.  Look at the values of sdf["HDU"] and see if you can do sdf.select() on them

**Comment by teuben** [comment]
I can confirm the data is correct in the junk60.fits, the bintables are different and compared well with the bintable in junk620 and junk621.

**Comment by teuben** [comment]
Perhaps that hdu= in gettp() is an error, but the following now baffles me that on an SDFITS with many BINTABLES this fails:
```
GBTFITSLoad('junk62.fits', hdu=2).gettp(scan=62, ifnum=0, plnum=0)[0]._index[k][:1]
```
