### ISSUE TITLE
dysh-lab out of date with release branch

### ISSUE THREAD

**Issue by jfrothingham** [GreenBankObservatory/dysh#364]
**Describe the bug**
What is the bug? What did you expect to happen vs. what actually happened?
The version of dysh that comes installed with dysh-lab is not up to date with the current release branch in Github. 

As per https://github.com/GreenBankObservatory/dysh/releases/tag/0.3.0, a fix for Issue 256 was merged into the release branch. Not sure if there's something I can do to force an update of the dysh installation as opened with dysh-lab.

**How to Reproduce**
Ran `dysh-lab` on a Green Bank data reduction machine and opened a Jupyter notebook
Running `dysh.__version__` in the notebook shows that the version is "0.3.0"
`sdfits = GBTFITSLoad('filepath')`
`sdfits.gettp(scan=7, ifnum=0, plnum=0).timeaverage()` produces "ValueError: Coordinate frame name "" is not a known coordinate frame (['altaz', 'barycentricmeanecliptic', 'barycentrictrueecliptic', 'cirs', 'custombarycentricecliptic', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentricmeanecliptic', 'geocentrictrueecliptic', 'hadec', 'hcrs', 'heliocentriceclipticiau76', 'heliocentricmeanecliptic', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'lsrd', 'lsrk', 'precessedgeocentric', 'supergalactic', 'teme', 'tete'])"

This is Issue 256 showing up again (or rather, still showing up).

**Comment by astrofle** [comment]
Hi Jay,
As you pointed out in https://github.com/GreenBankObservatory/dysh/issues/256, the problem had not fixed after the merge of https://github.com/GreenBankObservatory/dysh/pull/264 (I'm not sure why it wasn't fixed at that time).

I can think of two options for having access to the fix. One is to wait for the next release (end of year), or installing your own version of dysh at GBO in one of the data reduction machines:
```bash
/users/gbosdd/python/bin/python3.11 -m venv /home/scratch/$USER/dysh-venv # Create a new virtual environment with Python3.11
source /home/scratch/$USER/dysh-venv/bin/activate # Activate it
python -m pip install "dysh[nb] @ git+https://github.com/GreenBankObservatory/dysh" # Install dysh and jupyterlab
cd your/working/dir # Go to the directory with your notebooks, if needed
dysh-lab # Launch jupyterlab (assuming you have access to a display, if not, use the --no-browser option)
```
I'll close the issue for now, but please re-open it if you run into this issue again.
