### ISSUE TITLE
in timeaverage() methods make sure header (meta) variables are correct

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#38]
e.g.  EXPOSURE should be summed. Tsys should be average. etc.

**Comment by astrofle** [comment]
Implemented for `GBTTPScan` in  [0a7fe37](https://github.com/GreenBankObservatory/dysh/commit/0a7fe376a5df786c5b5857b25c2258d12c0d0f39)

**Comment by astrofle** [comment]
Implemented for `PSScan` in [6bde9e5](https://github.com/GreenBankObservatory/dysh/commit/6bde9e5e053d7b78fca4cbc22f1ac075767dfbc7)
