### ISSUE TITLE
GBTFITSLoad gives cryptic error message when a directory is used with no fits files

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#381]
**Describe the bug**
If GBTFITSLoad() is given a directory name with no fits files, the error message is too cryptic for most users

**How to Reproduce**

```
!mkdir junk124
GBTFITSLoad('junk123')
.....
AttributeError: 'NoneType' object has no attribute 'keys'
```

If a blank fits file is in this directory, it correctly says there is a corrupt fits file.

**Environment**
- Dysh version 0.3.0
- Python version 3.10.14
- OS kubuntu 22.04

**Comment by mpound** [comment]
this is an easy fix, I will patch it has part of flagging.    At line 76:
            if len(self._sdf) == 0:
                 raise Exception(f"No FITS files found in {fileobj}.")

**Comment by mpound** [comment]
fixed.  in main now.
