### ISSUE TITLE
Missing INTNUMs

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#390]
**Describe the bug**
When checking the integration numbers (column INTNUM) for a `GBTFITSLoad` object, for one of the spectral windows INTNUM starts at 12 even though it should start at 0.

**How to Reproduce**
The data paths are for GBO.

Load a file, select rows for IF 3 and scan 13.
```Python
from dysh.fits import GBTFITSLoad
sdf = GBTFITSLoad("/home/dysh/acceptance_testing/data/AGBT12A_076_05/AGBT12A_076_05.raw.acs")
mask = ( sdf["IFNUM"] == 3 ) & ( sdf["SCAN"] == 13 )
sdf["TIMESTAMP", "INTNUM"][mask]
```
that prints
```Python

TIMESTAMP | INTNUM
-- | --
2013_05_04_13:11:29 | 12
2013_05_04_13:11:29 | 12
2013_05_04_13:11:29 | 12
2013_05_04_13:11:29 | 12
2013_05_04_13:11:29 | 13
... | ...
2013_05_04_13:11:29 | 46
2013_05_04_13:11:29 | 47
2013_05_04_13:11:29 | 47
2013_05_04_13:11:29 | 47
2013_05_04_13:11:29 | 47

96 rows × 2 columns
```
For the same scan, but IF 0
```Python
mask = ( sdf["IFNUM"] == 0 ) & ( sdf["SCAN"] == 13 )
sdf["TIMESTAMP", "INTNUM"][mask]
```
prints
```Python

TIMESTAMP | INTNUM
-- | --
2013_05_04_13:11:29 | 0
2013_05_04_13:11:29 | 0
2013_05_04_13:11:29 | 0
2013_05_04_13:11:29 | 0
2013_05_04_13:11:29 | 1
... | ...
2013_05_04_13:11:29 | 34
2013_05_04_13:11:29 | 35
2013_05_04_13:11:29 | 35
2013_05_04_13:11:29 | 35
2013_05_04_13:11:29 | 35

96 rows × 2 columns
```

Notice that the first item has the same time stamp for both IFs, but the IF 3 starts with INTNUM 12 instead of 0 (like IF 0).

**Environment**
- Dysh version 0.4.0a
- Python version 3.9
- OS RH7

**Comment by teuben** [comment]
Note this is the "nod9" example in my test_nodding.py - also reported in #376

**Comment by mpound** [comment]
INTNUM is not a default column created by the SDFITS writer.   If the data have been passed through GBTIDL, then GBTIDL writes a new INTNUM column.    So dysh must deal with two cases:
1) No INTNUM column, in which case dysh creates it from scratch.  In this case it runs from zero to n_integrations-1 and resets to zero at a new scan.   
 2) GBTIDL already created it, so dysh accepts that.    I deliberately chose not to rewrite INTNUM because users would expect it to be the same what they see in GBTIDL.

A corrollary to 2) is that if we have trimmed down a SDFITS file that already has INTNUM, then the INTNUMs may no longer start at zero.

**Comment by astrofle** [comment]
> INTNUM is not a default column created by the SDFITS writer. If the data have been passed through GBTIDL, then GBTIDL writes a new INTNUM column. So dysh must deal with two cases:
> 
> 1. No INTNUM column, in which case dysh creates it from scratch.  In this case it runs from zero to n_integrations-1 and resets to zero at a new scan.
> 2. GBTIDL already created it, so dysh accepts that.    I deliberately chose not to rewrite INTNUM because users would expect it to be the same what they see in GBTIDL.
> 
> A corrollary to 2) is that if we have trimmed down a SDFITS file that already has INTNUM, then the INTNUMs may no longer start at zero.


Noted. However, for this example, the original file does not have an INTNUM column:
```Python
from astropy.io import fits
filename = "/home/dysh/acceptance_testing/data/AGBT12A_076_05/AGBT12A_076_05.raw.acs/AGBT12A_076_05.raw.acs.fits"
hdu = fits.open(filename)
table = hdu[1].data
print("INTNUM" in table.names)
    False
```

**Comment by teuben** [comment]
Also to note, this is the file where the PROCSCAN column (which was supposed to have the values BEAM1 or BEAM2) as just the value 'Unknown'.

Is this an upstream instrument problem, or a bug in the sdfits writer I was wondering.

**Comment by astrofle** [comment]
> Also to note, this is the file where the PROCSCAN column (which was supposed to have the values BEAM1 or BEAM2) as just the value 'Unknown'.
> 
> Is this an upstream instrument problem, or a bug in the sdfits writer I was wondering.

I think the use of PROCSCAN was added after that observation took place. Querying projects from the same year using Nod also show that that keyword is missing.
