### ISSUE TITLE
Changing the frame of a Spectrum to itself changes its spectral axis

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#401]
**Describe the bug**
When changing the frame of a `Spectrum` to its `_velocity_frame`, the resulting `Spectrum` has a different `SpectralAxis`, even though they should be the same.

**How to Reproduce**
```Python
from dysh.spectra import Spectrum
spec = Spectrum.fake_spectrum()
(spec.with_frame(spec._velocity_frame).spectral_axis.value - spec.spectral_axis.value).sum() == 0
    False
```

**Environment**
- Dysh version 0.4.0a
- Python version 3.9
- OS RH7

**Comment by mpound** [comment]
The problem is that Spectrum.observer != Spectrum.spectral_axis.observer after the call to `with_frame()`.
While investigating this issue, I found a related astropy bug, now filed at https://github.com/astropy/astropy/issues/17506
