### ISSUE TITLE
Suppress warning when loading with `GBTFITSLoad`

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#42]
When loading a file with `dysh.fits.GBTFITSLoad` a warning about units is issued. This should be ignored or fixed at some point. 
I don't think this is a requirement for Q1.

**Comment by mpound** [comment]
yeah, this can be suppressed by locally defining mmHg.  with units.def_unit.  mmHg is not standard FITS

**Comment by astrofle** [comment]
I have not seen the issue while working in the multifits branch. Thanks Marc!
