### ISSUE TITLE
Removing flags

### ISSUE THREAD

**Issue by astrofle** [GreenBankObservatory/dysh#427]
**Describe the bug**
I wanted to clear the flags on a GBTFITSLoad object, but after calibration the flags are still there.

**How to Reproduce**
```Python
from pathlib import Path
import matplotlib.pyplot as plt
from dysh.util.download import from_url
from dysh.fits.gbtfitsload import GBTFITSLoad

url = "http://www.gb.nrao.edu/dysh/example_data/positionswitch/data/AGBT05B_047_01/AGBT05B_047_01.raw.acs/AGBT05B_047_01.raw.acs.fits"
savepath = Path.cwd() / "data"
filename = from_url(url, savepath)

sdf = GBTFITSLoad(filename)

sdf.flags.clear()

# Flag some data.
sdf.flag(scan=51, intnum=5, channel=[[1000,5000]])
pssb = sdf.getps(scan=51, plnum=0, apply_flags=True)

# Show results
plt.figure(dpi=150)
plt.imshow(pssb[0]._calibrated, origin="lower", aspect="auto")

# Remove flags and repeat.
sdf.flags.clear()
sdf.flags.show()
pssb = sdf.getps(scan=51, plnum=0, apply_flags=True)
plt.figure(dpi=150)
plt.imshow(pssb[0]._calibrated, origin="lower", aspect="auto")
# The data is still flagged, even if there are no flags.
```
<img width="377" alt="Screenshot 2024-11-22 at 12 47 37 PM" src="https://github.com/user-attachments/assets/9608bba1-8e3c-4386-b062-2db295d8ba85">
<img width="377" alt="Screenshot 2024-11-22 at 12 47 49 PM" src="https://github.com/user-attachments/assets/49691423-52d8-4f4f-9ed7-89adabebe38e">

**Environment**
- Dysh version 0.4.0a
- Python version 3.10
- OS

**Comment by mpound** [comment]
This is not a bug.  You should use GBTFITSLoad.clear_flags() to clear the flags.   sdf.flags.clear() clears the flag RULES from the Flag object.   It doesn't have an effect on the _flag array because that is not contained in the Flag object.    

I welcome suggestions on how to document this better.

**Comment by astrofle** [comment]
Thanks for pointing to the existence of `GBTFITSLoad.clear_flags()`. I think we should show how to clear the flags using this method in one of the example notebooks.

**Comment by astrofle** [comment]
Added this to the flagging example. Closing for now.
