### ISSUE TITLE
Determine whether black will be used to autoformat code

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#48]
I have created #47 . Its goal is to determine the viability of using Black as dysh's auto-formatter. I used a line length of 120 characters, to try to keep vertical space to a minimum. But it probably should be shorter if you want cleaner diffs in GitHub UI

You can read more about the Black style here https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html

Discussion should probably be in this issue, as there will potentially be additional PRs if you all want to move forward with this

**Comment by astrofle** [comment]
Thanks a lot Thomas!
The changes look good to me. I'd like to test it before moving forward. When working with Kasey on the `gbtgridder` I think we were using Black, but it was giving me warnings every time I tried to push something -- it made the development more annoying on my end. I'll report after I've tried it out.

**Comment by mpound** [comment]
So far I like what I see!   It doesn't look all that different from the pre-black code.

**Comment by teuben** [comment]
is it true that things like

      UT      = ' 19:21:11.948'              #  Universal time at start
      LST     = ' 14:00:19.050'              #  Sideral time at start

would get reformatted so things don't align.

I'll repeat my very strong reservation against this.   There's a very good reason, actually very pythonesque, that you align such things to be readable, so errors are caught.

If black blanket reformats my space, that's nuts. I can think of a few other examples which I frequently use in C code to align  comments for readability.

Can we have an unblack so we edit in peace?

**Comment by mpound** [comment]
You can control this with # fmt: off  , # fmt: on  
If you run black on the following file you will see what I mean.  (I had to gzip it to make github attach it).

[foo.py.gz](https://github.com/GreenBankObservatory/dysh/files/12899309/foo.py.gz)

**Comment by mpound** [comment]
We have agreed to use black and we may rarely use the special invocation to have black ignore certain lines.   Here it is turned off until it is turned back on again:

UT      = ' 19:21:11.948'              #  fmt: off
LST     = ' 14:00:19.050'             #  
some_other_thing = "blah blah"  # fmt: on
