### ISSUE TITLE
Dependency version pinning

### ISSUE THREAD

**Issue by tchamberlin** [GreenBankObservatory/dysh#51]
Currently `requirements.txt` and `requirements_dev.txt` don't have explicit version pins in them. This means that the same commit's tests might execute differently today vs 1 month from now, if e.g. Astropy has released some breaking change

Hatch doesn't provide any dependency management (i.e. a lockfile, like you'd find in Poetry or PDM), so I'd recommend using [pip-tools](https://github.com/jazzband/pip-tools) to manage these. That lets you avoid managing requirements files by hand, but also pins explicit package versions for each commit

**Comment by mpound** [comment]
I try to avoid version pinning except by using >= when required.    It can aggravate users if, e.g. we are pinned to a certain astropy version, but some other package they have is pinned to another.  I suspect most users don't create a venv for every package they use. 

That being said, I have been bitten when trying to manually keep version pinning in sync.  Does pip-tools figure out for instance, that astropy version X requires matplotlib version>Y?

**Comment by tchamberlin** [comment]
This doesn't affect end users at all. For us, the purpose is solely for test reproducibility. For other projects, e.g. web servers, it would allow you to reproduce the known-good environment that all your tests ran against, in production.

The idea is that you have very minimal pins in `pyproject.toml`, as you indicate. But that leaves you open to tests acting differently depending on whether a dependency has released an update or not. So you have some concept of a "lock file". In Poetry that's `poetry.lock`, PDM is `pdm.lock`. Hatch doesn't have a lock file, but we can use `pip-compile` to accomplish basically the same thing.

So, the only people using the requirements files are developers and the automated tests.
