### ISSUE TITLE
Makefile broken for new docs directory structure

### ISSUE THREAD

**Issue by mpound** [GreenBankObservatory/dysh#90]
make fails in src/dysh/docs, e.g.

make html
Running Sphinx v6.1.3

Configuration error:
config directory doesn't contain a conf.py file (/home/mpound/src/dysh/docs)
make: *** [Makefile:20: html] Error 2

This is because conf.py was move to the source directory.   
There are two possible solutions
1) move Makefile to source.  However this pollutes the source directory with _build. 
2) move conf.py to docs.   Then it needs to be modified so that e.g. make html works.  

As it is I don't see how readthedocs for version 0.2.0 was succeeding.

**Comment by vcatlett** [comment]
See https://github.com/GreenBankObservatory/dysh/pull/96
