### ISSUE TITLE
positionswitch notebook example fails for me

### ISSUE THREAD

**Issue by teuben** [GreenBankObservatory/dysh#91]
This notebook fails for me, there's no signal in it compared to the saved output.

Also, the user could be told what expected answers are, e.g.  I found  T_sys = 17.24

**Comment by teuben** [comment]
How about adding a regression test.  using

   jupyter nbconvert --to script blabla.ipynb

we could add a regression that can be captured and verified during build.

**Comment by teuben** [comment]
it's also frustrating for a newcomer to have to hunt down the data file, since the f= doesn't exist on most users' machines.
I could add a comment cell like this:

The datafile in this example lives in $DYSH/src/dysh/fits/tests/data/TGBT21A_501_11.raw.vegas.fits or ../../src/dysh/fits/tests/data/TGBT21A_501_11.raw.vegas.fits from the examples directory

but this could also be a good example where that  fits finder tool I wrote could be used

**Comment by astrofle** [comment]
Thanks for checking that Peter.
Would something like this be better for the contents of the notebook?
https://dysh.readthedocs.io/en/pedro-devel/getting_started/tutorials/GBT/tutorial-positionswitch.html

**Comment by teuben** [comment]
not my lucky day.   I tried the release 0.1.0 but this failed with sdfitsload::udata not knowing the utils  module. This happened in the sdfits = GBTFITSLoad(filename) command.

Not to worry too much, in 0.2.0 it's ok, but that's not released yet.

But back to worries: the plot from ta.plot() however does exhibit the same problem as I had before.

I then realized I cheated and use the same name (!!) file in our tests area. That's a much smaller file and does not reproduce the example. So I guess we never properly named the files which were taken as a subset of the original ones?

**Comment by teuben** [comment]
so, in the end the confusion is because I took the (same named!!!)   fits file from the test area, not being at GBT.
So the notebook should really give the wget() argument like the tutorial does, plus remind the users it's nearly 800MB.

**Comment by teuben** [comment]
I made a reproducible 0.1.0 case to see if I can get it to fail, but could not. I blame that earlier report on a pilot error.

The only issue remaining here is that we steal the original filename in tests¸thus causing confusion between the large wget version in  the tutorial vs. the smaller same name file in the source tree.

**Comment by mpound** [comment]
Fixed on 0.2.0
